const exerciseImages = {
  "barbell bent over row": "/assets/exercises/barbell_bent_over_row.png",
  "placeholder": "/assets/exercises/placeholder.png",
  "alternate lateral pulldown": "/assets/exercises/alternate_lateral_pulldown.png",
  "barbell pullover to press": "/assets/exercises/barbell pullover to press.png",
  "barbell decline wide-grip pullover": "/assets/exercises/barbell decline wide-grip pullover.png",
  "barbell pullover": "/assets/exercises/barbell pullover.png",
  "assisted pull-up": "/assets/exercises/assisted pull-up.png",
  "barbell bench press": "/assets/exercises/barbell bench press.png",
  "barbell incline shoulder raise": "/assets/exercises/barbell incline shoulder raise.png",
  "barbell guillotine bench press": "/assets/exercises/barbell guillotine bench press.png",
  "barbell decline wide-grip press": "/assets/exercises/barbell decline wide-grip press.png",
  "cable bench press": "/assets/exercises/cable bench press.png",
  "barbell one arm snatch": "/assets/exercises/barbell one arm snatch.png",
  "barbell rear delt row": "/assets/exercises/barbell rear delt row.png",
  "barbell rear delt raise": "/assets/exercises/barbell rear delt raise.png",
  "barbell seated bradford rocky press": "/assets/exercises/barbell seated bradford rocky press.png",
  "barbell seated overhead press": "/assets/exercises/barbell seated overhead press.png",
  "barbell standing front raise over head": "/assets/exercises/barbell standing front raise over head.png",
  "barbell front raise": "/assets/exercises/barbell front raise.png",
  "barbell skier": "/assets/exercises/barbell skier.png",
  "barbell reverse wrist curl": "/assets/exercises/barbell reverse wrist curl.png",
  "barbell standing back wrist curl": "/assets/exercises/barbell standing back wrist curl.png",
  "cable reverse wrist curl": "/assets/exercises/cable reverse wrist curl.png",
  "cable standing back wrist curl": "/assets/exercises/cable standing back wrist curl.png",
  "dumbbell lying pronation": "/assets/exercises/dumbbell lying pronation.png",
  "barbell standing leg calf raise": "/assets/exercises/barbell standing leg calf raise.png",
  "barbell standing rocking leg calf raise": "/assets/exercises/barbell standing rocking leg calf raise.png",
  "circles knee stretch": "/assets/exercises/circles knee stretch.png",
  "dumbbell seated one leg calf raise": "/assets/exercises/dumbbell seated one leg calf raise.png",
  "dumbbell single leg calf raise": "/assets/exercises/dumbbell single leg calf raise.png",
  "lever standing calf raise": "/assets/exercises/lever standing calf raise.png",
  "dumbbell standing calf raise": "/assets/exercises/dumbbell standing calf raise.png",
  "lever seated calf raise": "/assets/exercises/lever seated calf raise.png",
  "dumbbell alternate side press": "/assets/exercises/dumbbell alternate side press.png",
  "dumbbell around pullover": "/assets/exercises/dumbbell around pullover.png",
  "dumbbell bench seated press": "/assets/exercises/dumbbell bench seated press.png",
  "dumbbell bench squat": "/assets/exercises/dumbbell bench squat.png",
  "dumbbell biceps curl": "/assets/exercises/dumbbell biceps curl.png",
  "dumbbell bent over row": "/assets/exercises/dumbbell bent over row.png",
  "dumbbell alternate biceps curl": "/assets/exercises/dumbbell alternate biceps curl.png",
  "barbell curl": "/assets/exercises/barbell curl.png",
  "barbell bench front squat": "/assets/exercises/barbell bench front squat.png",
  "barbell clean-grip front squat": "/assets/exercises/barbell clean-grip front squat.png",
  "barbell alternate biceps curl": "/assets/exercises/barbell alternate biceps curl.png",
   "push up on bosu ball": "/assets/exercises/push up on bosu ball.png",
  "squat on bosu ball": "/assets/exercises/squat on bosu ball.png",
  "walk elliptical cross trainer": "/assets/exercises/walk elliptical cross trainer.png",
  "cable alternate triceps extension": "/assets/exercises/cable alternate triceps extension.png",
  "cable alternate shoulder press": "/assets/exercises/cable alternate shoulder press.png",
  "cable bar lateral pulldown": "/assets/exercises/cable bar lateral pulldown.png",
  "cable cross-over lateral pulldown": "/assets/exercises/cable cross-over lateral pulldown.png",
  "cable deadlift": "/assets/exercises/cable deadlift.png",
  "cable cross-over variation": "/assets/exercises/cable cross-over variation.png"
};

export default exerciseImages;